[project]
name = "modtomc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.0, <3.12"
dependencies = [
    "numpy>=2.3.2",
    "open3d>=0.19.0",
    "trimesh>=4.7.4",
]
